server:
  port: 8087
spring:
  profiles:
    active: dev
  messages:
    basename: i18n.messages
  datasource:
    druid:
      initial-size: 10
      max-active: 500
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.rpay.model
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_NULL
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

fs:
  #多租户应用隔离配置
  tenant:
    enable: false
    ignoreTables:
    - sys_user
    - sys_user_role
    - sys_role_auth
    - sys_role
    - sys_auth
  # 云存储配置
  files-server:
    type: fds
    #local:
      #uploadPath: D:/data/upload  #windows
      #upload-path: /home/data/upload   #linux
      #nginx映射本地目录的url，需自己配置
      #ngxinxUrl: http://localhost:4344/resource
    #qiniu:
      #accessKey: xxxxxxxxxxxxxxxxxxx
      #secretKey: xxxxxxxxxxxxxxxxxxx
      #bucket: xxxxxxxxxxxxxxxxxxx
      #path: xxxxxxxxxxxxxxxxxxx
    #oss配置
    oss:
      accessKey: LTAI5tNCe5tPPVrqkKhsUC7r
      secretKey: PobQsIubrCpQqpHxvZEvia79vl63AW
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket: tbruce
      path: /data/testUpload
    fds:
      conf: classpath:fdfs_client.conf
      fastdfs:
        connect_timeout_in_seconds: 2
        network_timeout_in_seconds: 30
        charset: UTF-8
        http_tracker_http_port: 8888
        tracker_servers: 127.0.0.1:22122
