spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rpay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: BHdfh^4d!k
    driver-class-name: com.mysql.cj.jdbc.Driver

fs:
  isPreview: false
